name: Permission

on:
  push:
    branches:
      - main

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directory before
      run: ls -alh

    - name: File permission
      run: chmod -R 777 pp.png

    - name: List directory after
      run: ls -alh

