name: Create Blank File

on:
  push:
    branches:
      - main

jobs:
  create-blank-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List directory before
      run: ls -al

    - name: Create blank testing.php file
      run: touch testing.php

    - name: List directory after
      run: ls -al
