name: Create File

on: 
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create testing.php file
      run: echo "Hello World" > testing.php
