name: Create A File
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ "main" ]

jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create testing.php file
      run: echo "Hello World" > testing.php
